steps:
- task: NodeTool@0
  displayName: 'Use Node 16.x'
  inputs:
    versionSpec: 16.x

- task: Npm@1
  displayName: 'npm install'

- script: npm install
  displayName: 'npm install (script)'
  condition: always()

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run build
