steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: Npm@1
  displayName: 'npm install'

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run build
